"""
Django settings for towercell project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "y", "on")


def _env_csv(name: str) -> list[str]:
    return [p.strip() for p in os.getenv(name, "").split(",") if p and p.strip()]


def _load_dotenv(path: Path) -> None:
    """
    Minimal .env loader for local development (no external dependency).
    - Does not override existing environment variables.
    - Supports simple KEY=VALUE lines with optional quotes.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        if key and key not in os.environ:
            os.environ[key] = value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local `manage.py runserver` usage (docker-compose already injects env_file).
_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

SECRET_KEY = (os.getenv("DJANGO_SECRET_KEY") or os.getenv("SECRET_KEY") or "").strip()
if not SECRET_KEY and DEBUG:
    # Dev fallback only. In production provide DJANGO_SECRET_KEY.
    SECRET_KEY = "django-insecure-dev-only"
if not DEBUG and (not SECRET_KEY or SECRET_KEY.startswith("django-insecure")):
    raise ValueError("DJANGO_SECRET_KEY must be set to a strong value when DJANGO_DEBUG=false")

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = _env_csv("DJANGO_ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"] if DEBUG else []
if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError("DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG=false")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "cellular",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'TowerCell Geolocation API',
    'DESCRIPTION': '''
Network-based geolocation API using cell tower signals.

## Quick start
1. Open **/api/v1/schema/swagger-ui/** to browse and try endpoints.
2. Pick an endpoint, click **Try it out**, then **Execute**.
3. For authenticated endpoints, use **Authorize** in Swagger UI.

## What this API does
- Estimates user location from nearby cell towers (multilateration + signal models)
- Provides tower search and import utilities
- Includes calibration helpers (path-loss exponent, reference loss)

## Notes
- Input/output formats are documented per endpoint in Swagger.
- Error responses include an `error` message and may include `details`.
''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    # Use bundled static assets from `drf-spectacular-sidecar` for Swagger UI.
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    # Swagger UI UX tweaks (no custom HTML/CSS).
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayRequestDuration': True,
        'docExpansion': 'none',
        'filter': True,
        'persistAuthorization': True,
        'defaultModelsExpandDepth': -1,
        'defaultModelExpandDepth': 2,
        'tryItOutEnabled': True,
        'syntaxHighlight': {'activate': True},
    },
    'CONTACT': {
        'name': 'API Support',
        'email': 'javadandroid@gmail.com',
    },
    'LICENSE': {
        'name': 'ONE',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'towercell.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Project-level templates. We keep `BASE_DIR/templates` as the conventional
        # location and also include `towercell/templates` since the current
        # `home.html` lives there.
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'towercell' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'towercell.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_BACKEND = os.getenv("DJANGO_DB_BACKEND", "sqlite").lower()

if DB_BACKEND == "postgres":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'towercell'),
            'USER': os.getenv('POSTGRES_USER', 'towercell'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== CORS ====================
_EXTRA_CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if o and o.strip()
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    *_EXTRA_CORS_ALLOWED_ORIGINS,
]

CORS_ALLOW_CREDENTIALS = True

# Allow CSRF from local frontend
_EXTRA_CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o and o.strip()
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    *_EXTRA_CSRF_TRUSTED_ORIGINS,
]

# ==================== Positioning / Path-Loss Defaults ====================
# These defaults can be overridden via environment-specific settings.
PATH_LOSS = {
    # Default transmit power (dBm) to use when tower TX unknown
    'TX_DEFAULT': 40,
    # Default path-loss exponent for dense urban areas (calibrated)
    'N_DEFAULT': 2.6145,
    # Reference loss at 1 meter (dB)
    'REF_LOSS': 80,
}

# ==================== Towers / Map Defaults ====================
MAX_TOWERS_PER_REQUEST = int(os.getenv("TOWERS_MAX_LIMIT", 50))

# ==================== Snapshot Locate (External API) ====================
# Security: this feature fetches JSON from an external API, so we enforce an allowlist.
# Example:
#   SNAPSHOT_ALLOWED_HOSTS=api.example.com,staging.api.example.com
SNAPSHOT_ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("SNAPSHOT_ALLOWED_HOSTS", "").split(",")
    if h and h.strip()
]

# ==================== Import API Key (optional) ====================
# If set, CSV import endpoints require `X-API-KEY: <IMPORT_API_KEY>` and do not need login.
IMPORT_API_KEY = os.getenv("IMPORT_API_KEY", "").strip()

# ==================== External Tower Resolver ====================
COMBAIN_API_KEY = os.getenv("COMBAIN_API_KEY", "").strip()
GOOGLE_GEOLOCATION_API_KEY = os.getenv("GOOGLE_GEOLOCATION_API_KEY", "").strip()


# If enabled, snapshot neighbor towers may be resolved via external APIs (paid).
ALLOW_EXTERNAL_NEIGHBOR_LOOKUP = _env_bool("ALLOW_EXTERNAL_NEIGHBOR_LOOKUP", False)
