"""
Django settings for towercell project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


def _load_dotenv(path: Path) -> None:
    """
    Minimal .env loader for local development (no external dependency).
    - Does not override existing environment variables.
    - Supports simple KEY=VALUE lines with optional quotes.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'").strip('"')
        if key and key not in os.environ:
            os.environ[key] = value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local `manage.py runserver` usage (docker-compose already injects env_file).
_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nf*#(fbx+3v=)re$%qqq-ha08v7(95o)97%=_@thdv%52+t1&9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "cellular",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': '🗺️ TowerCells RD - Geolocation API',
    'DESCRIPTION': '''سیستم موقعیت‌یابی شبکه‌ای ایران
    
    **بر اساس داده‌های دکل‌های سلولی (Cell Tower Geolocation)**
    
    ### ویژگی‌ها:
    - الگوریتم Trilateration
    - فرمول Path Loss Model
    - محاسبه جهت (Bearing)
    - جبران انحراف (Back Lobe Correction)
    
    ### منابع داده:
    - دیتابیس محلی
    - API OpenCellID
    - War Driving Collection
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Local Development'},
        {'url': 'https://api.towercells.ir', 'description': 'Production'},
    ],
    'CONTACT': {
        'name': 'API Support',
        'email': 'support@towercells.ir',
    },
    'LICENSE': {
        'name': 'MIT',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'towercell.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'towercell.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_BACKEND = os.getenv("DJANGO_DB_BACKEND", "sqlite").lower()

if DB_BACKEND == "postgres":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'towercell'),
            'USER': os.getenv('POSTGRES_USER', 'towercell'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== CORS ====================
_EXTRA_CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")
    if o and o.strip()
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    *_EXTRA_CORS_ALLOWED_ORIGINS,
]

CORS_ALLOW_CREDENTIALS = True

# Allow CSRF from local frontend
_EXTRA_CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o and o.strip()
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    *_EXTRA_CSRF_TRUSTED_ORIGINS,
]

# ==================== Positioning / Path-Loss Defaults ====================
# These defaults can be overridden via environment-specific settings.
PATH_LOSS = {
    # Default transmit power (dBm) to use when tower TX unknown
    'TX_DEFAULT': 40,
    # Default path-loss exponent for dense urban areas (calibrated)
    'N_DEFAULT': 2.6145,
    # Reference loss at 1 meter (dB)
    'REF_LOSS': 80,
}

# ==================== Towers / Map Defaults ====================
MAX_TOWERS_PER_REQUEST = int(os.getenv("TOWERS_MAX_LIMIT", 50))

# ==================== Snapshot Locate (External API) ====================
# Security: this feature fetches JSON from an external API, so we enforce an allowlist.
# Example:
#   SNAPSHOT_ALLOWED_HOSTS=api.example.com,staging.api.example.com
SNAPSHOT_ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("SNAPSHOT_ALLOWED_HOSTS", "").split(",")
    if h and h.strip()
]

# ==================== Import API Key (optional) ====================
# If set, CSV import endpoints require `X-API-KEY: <IMPORT_API_KEY>` and do not need login.
IMPORT_API_KEY = os.getenv("IMPORT_API_KEY", "").strip()

# ==================== External Tower Resolver ====================
COMBAIN_API_KEY = os.getenv("COMBAIN_API_KEY", "").strip()
GOOGLE_GEOLOCATION_API_KEY = os.getenv("GOOGLE_GEOLOCATION_API_KEY", "").strip()


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "y", "on")


# If enabled, snapshot neighbor towers may be resolved via external APIs (paid).
ALLOW_EXTERNAL_NEIGHBOR_LOOKUP = _env_bool("ALLOW_EXTERNAL_NEIGHBOR_LOOKUP", False)
