# Generated by Django 6.0 on 2025-12-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellTower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_type', models.CharField(choices=[('gsm', '2G (GSM)'), ('wcdma', '3G (WCDMA)'), ('lte', '4G (LTE)'), ('nr', '5G (NR)')], default='lte', help_text='Type of Radio (e.g., GSM, LTE, NR)', max_length=10)),
                ('mcc', models.IntegerField(help_text='Mobile Country Code (e.g., 432)')),
                ('mnc', models.IntegerField(help_text='Mobile Network Code (e.g., 35)')),
                ('lac', models.IntegerField(blank=True, help_text='Location Area Code / TAC', null=True)),
                ('cell_id', models.BigIntegerField(blank=True, help_text='CID / ECI (Identity)', null=True)),
                ('pci', models.IntegerField(blank=True, help_text='Physical Cell ID (0-503)', null=True)),
                ('earfcn', models.IntegerField(blank=True, help_text='Frequency Channel', null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('tx_power', models.IntegerField(default=40, help_text='Transmission Power in dBm (Default: 40 for Urban Macro)')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('API', 'Fetched from External API'), ('WARD', 'War Driving Collection')], default='API', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mcc', 'mnc', 'pci'], name='cellular_ce_mcc_46b31c_idx')],
                'unique_together': {('mcc', 'mnc', 'cell_id', 'lac')},
            },
        ),
    ]
