# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CellTower",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("radio_type", models.CharField(choices=[("gsm", "2G (GSM)"), ("umts", "3G (WCDMA، TD-CDMA, TD-SCDMA)"), ("lte", "4G (LTE)"), ("nr", "5G (NR)")], default="lte", help_text="Type of Radio (e.g., GSM, LTE, NR)", max_length=10)),
                ("mcc", models.IntegerField(help_text="Mobile Country Code (e.g., 432)")),
                ("mnc", models.IntegerField(help_text="Mobile Network Code (e.g., 35)")),
                ("lac", models.IntegerField(blank=True, help_text="Location Area Code / TAC", null=True)),
                ("cell_id", models.BigIntegerField(blank=True, help_text="CID / ECI (Identity)", null=True)),
                ("pci", models.IntegerField(blank=True, help_text="Physical Cell ID (0-503)", null=True)),
                ("earfcn", models.IntegerField(blank=True, help_text="Frequency Channel", null=True)),
                ("range_m", models.IntegerField(blank=True, help_text="Coverage range in meters", null=True, verbose_name="Tower Range")),
                ("is_approximate", models.BooleanField(default=True, help_text="Indicates if the location is approximate")),
                ("samples", models.IntegerField(blank=True, help_text="Total number of measurements assigned to the cell tower", null=True)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("tx_power", models.IntegerField(default=42, help_text="Transmission Power in dBm (Default: 40 for Urban Macro)")),
                ("antenna_azimuth", models.IntegerField(blank=True, help_text="Optional antenna azimuth (degrees 0-360) for this tower", null=True)),
                ("source", models.CharField(choices=[("MLS", "Mozilla Location Service"), ("OPENCELLID", "OpenCellID"), ("MANUAL", "Manual Entry"), ("GOOGLE", "Google / Road Survey"), ("COMBAIN", "Combain"), ("OTHER", "Other / Unknown")], default="OTHER", help_text="Primary dataset source for this entry", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checked_count", models.PositiveIntegerField(default=0, help_text="Number of datasets that checked this tower")),
                ("verified_count", models.PositiveIntegerField(default=0, help_text="Number of datasets that verified this tower")),
            ],
            options={
                "unique_together": {("mcc", "mnc", "cell_id", "lac")},
                "indexes": [models.Index(fields=["mcc", "mnc", "pci"], name="cellular_ce_mcc_46b31c_idx")],
            },
        ),
    ]
