# Generated by Django 6.0 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cellular", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TowerLookupLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(max_length=20)),
                ("mcc", models.IntegerField(blank=True, null=True)),
                ("mnc", models.IntegerField(blank=True, null=True)),
                ("lac", models.IntegerField(blank=True, null=True)),
                ("cell_id", models.BigIntegerField(blank=True, null=True)),
                ("pci", models.IntegerField(blank=True, null=True)),
                ("earfcn", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("accuracy_m", models.FloatField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]

