# Generated by Django 6.0 on 2025-12-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celltower',
            name='antenna_azimuth',
            field=models.IntegerField(blank=True, help_text='Optional antenna azimuth (degrees 0-360) for this tower', null=True),
        ),
    ]
