# Generated by Django 6.0 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cellular", "0002_towerlookuplog"),
    ]

    operations = [
        migrations.AddField(
            model_name="towerlookuplog",
            name="request_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="towerlookuplog",
            name="request_body",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="towerlookuplog",
            name="response_body",
            field=models.JSONField(blank=True, null=True),
        ),
    ]

